---
# Source: apache/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: lamp-apache
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-8.5.1
    app.kubernetes.io/instance: lamp-apache
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: lamp-apache
---
# Source: apache/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-apache
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-8.5.1
    app.kubernetes.io/instance: lamp-apache
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apache
      app.kubernetes.io/instance: lamp-apache
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apache
        helm.sh/chart: apache-8.5.1
        app.kubernetes.io/instance: lamp-apache
        app.kubernetes.io/managed-by: Helm
    spec:
      
      # yamllint disable rule:indentation
      hostAliases:
        - hostnames:
          - status.localhost
          ip: 127.0.0.1
      # yamllint enable rule:indentation
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: apache
                    app.kubernetes.io/instance: lamp-apache
                namespaces:
                  - "ndc-app2"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      containers:
        - name: apache
          image: docker.io/bitnami/apache:2.4.46-debian-10-r218
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /healthcheck.html
              port: http
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthcheck.html
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: htdocs
              mountPath: /app
            - name: vhosts
              mountPath: /vhosts
      volumes:
        - name: htdocs
          
          configMap:
            name: apache-healthcheck
        - name: vhosts
          configMap:
            name: apache-conf
---
# Source: apache/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lamp-apache
  labels:
    app.kubernetes.io/name: apache
    helm.sh/chart: apache-8.5.1
    app.kubernetes.io/instance: lamp-apache
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "contour"
spec:
  rules:
    - host: app2.ndc.benoitmoussaud.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: lamp-apache
                port:
                  name: http
  tls:
    - hosts:
      - app2.ndc.benoitmoussaud.com
      secretName: app2-tls
