apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-php-fpm
  labels:
    app: lamp-php-fpm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lamp-php-fpm
      tier: backend
  template:
    metadata:
      labels:
        app: lamp-php-fpm
        tier: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: lamp-php-fpm
                  tier: backend
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: alexandreroman/ndc-php
        name: lamp-php-fpm
        ports:
        - containerPort: 9000
          name: lamp-php-fpm
        volumeMounts:
        - name: lamp-phpcontent
          mountPath: /app
      volumes:
      - name: lamp-phpcontent
        configMap:
          name: php-content
    